WITH questions (
  "sequence", "id", "senderSlot", "subject", "preview", "greeting", "body", "action", "attachmentName", "attachmentAsset", "suspicious", "explanation", "clues"
) AS (
  VALUES
  (1, 'reset-password-urgent', 1, 'Kata sandi berakhir dalam 10 menit', 'Perbarui sekarang agar akun tetap aktif.', 'Halo,', 'Sistem mendeteksi kata sandi lama. Masukkan kata sandi dan kode OTP untuk mencegah akun terkunci.', 'Buka: https://sekolah-reset.click/masuk', NULL, NULL, true, 'Email meminta kredensial, memakai ancaman waktu, dan mengarah ke domain yang bukan milik sekolah.', '[{"id":"sender","label":"Domain pengirim palsu","text":"Alamat pengirim memakai domain sekolah-share.click."},{"id":"body","label":"Meminta kredensial","text":"Email meminta kata sandi dan kode OTP."},{"id":"action","label":"Tautan tidak resmi","text":"Tautan mengarah ke sekolah-reset.click."}]'::jsonb),
  (2, 'class-schedule-safe', 2, 'Jadwal kelas minggu depan', 'Jadwal terbaru tersedia di portal sekolah.', 'Halo teman-teman,', 'Jadwal kelas minggu depan sudah diperbarui oleh wali kelas. Tidak ada data pribadi yang perlu dikirim melalui email.', 'Lihat: https://portal.sekolah.id/jadwal', 'jadwal-kelas.pdf', '/assets/Shared/Game/FileText.png', false, 'Pengirim dan tautan menggunakan domain resmi sekolah serta tidak meminta data rahasia.', '[]'::jsonb),
  (3, 'free-game-coins', 3, 'KOIN GAME GRATIS HARI INI', 'Klaim 10.000 koin sebelum kesempatan habis.', 'Pemain terpilih,', 'Akunmu memenangkan hadiah koin. Login dengan akun sekolah untuk mengambil hadiah sekarang.', 'Klaim: http://bonus-koin.win/login', NULL, NULL, true, 'Hadiah yang tidak diminta, permintaan login, dan domain asing merupakan pola phishing.', '[{"id":"sender","label":"Domain mencurigakan","text":"Alamat pengirim memakai domain hadiah-koin.win."},{"id":"subject","label":"Iming-iming hadiah","text":"Subjek menawarkan koin gratis secara mendesak."},{"id":"action","label":"Tautan berbahaya","text":"Tautan memakai domain bonus-koin.win."}]'::jsonb),
  (4, 'math-assignment-safe', 8, 'Tugas matematika bab 4', 'Pak Budi mengirim lembar latihan resmi.', 'Selamat sore,', 'Silakan kerjakan latihan bab 4 dan unggah jawaban melalui portal sekolah sebelum hari Jumat.', 'Unggah: https://portal.sekolah.id/tugas-matematika', 'latihan-bab-4.pdf', '/assets/Shared/Game/FileText.png', false, 'Instruksi sesuai konteks guru, memakai portal resmi, dan tidak meminta kredensial melalui email.', '[]'::jsonb),
  (5, 'library-fine-threat', 14, 'DENDA PERPUSTAKAAN WAJIB DIBAYAR SEKARANG', 'Bayar dalam 30 menit agar kartu tidak diblokir.', 'Yth. siswa,', 'Catatan kami menunjukkan denda besar. Masukkan nomor kartu dan PIN untuk membatalkan pemblokiran.', 'Bayar: https://perpus-bayar.top/form', NULL, NULL, true, 'Ancaman mendesak dan permintaan PIN melalui situs asing tidak sesuai prosedur perpustakaan.', '[{"id":"sender","label":"Alamat pengirim palsu","text":"Pengirim bukan dari domain sekolah.id."},{"id":"body","label":"Meminta PIN","text":"Email meminta nomor kartu dan PIN."},{"id":"action","label":"Situs pembayaran asing","text":"Tautan memakai domain perpus-bayar.top."}]'::jsonb),
  (6, 'art-event-safe', 11, 'Konfirmasi pameran komunitas seni', 'Detail waktu dan lokasi pameran akhir pekan.', 'Halo anggota komunitas,', 'Pameran akan berlangsung Sabtu pukul 10.00 di balai kota. Balas hanya jika kamu ingin mengubah jadwal penjagaan.', 'Info: https://komunitasseni.id/pameran', 'poster-pameran.png', '/assets/Shared/Game/FilePhoto.png', false, 'Pesan sesuai konteks komunitas, memakai domain resmi, dan tidak meminta informasi sensitif.', '[]'::jsonb),
  (7, 'otp-verification', 5, 'Verifikasi identitas staf sekolah', 'Kirim OTP untuk membuktikan bahwa kamu siswa aktif.', 'Hai,', 'Kami sedang memperbarui data siswa. Balas dengan kode OTP yang baru masuk ke ponselmu.', 'Balas email ini dalam 15 menit.', NULL, NULL, true, 'Pihak resmi tidak pernah meminta kode OTP. Batas waktu singkat digunakan untuk menekan penerima.', '[{"id":"sender","label":"Domain tiruan","text":"Alamat memakai domain update-sekolah.tech."},{"id":"body","label":"Meminta OTP","text":"Pesan meminta kode OTP melalui balasan email."},{"id":"action","label":"Tekanan waktu","text":"Penerima diminta membalas dalam 15 menit."}]'::jsonb),
  (8, 'environment-meeting-safe', 13, 'Rapat komunitas lingkungan', 'Agenda rapat bulanan dan daftar kegiatan.', 'Halo semuanya,', 'Rapat bulanan akan membahas penanaman pohon dan pembagian alat. Konfirmasi kehadiran lewat halaman komunitas.', 'Konfirmasi: https://komunitashijau.id/rapat', NULL, NULL, false, 'Alamat, isi, dan tautan konsisten dengan kegiatan resmi komunitas.', '[]'::jsonb),
  (9, 'shared-photo-malware', 6, 'Foto acara kelas untuk kamu', 'Unduh album foto dalam lampiran.', 'Halo,', 'Aku mengirim foto acara kemarin. Jalankan file terlampir agar album bisa dibuka dengan kualitas penuh.', 'Buka lampiran setelah diunduh.', 'AlbumFoto.exe', '/assets/Shared/Game/FileZip.png', true, 'Lampiran berekstensi .exe bukan berkas foto dan instruksi menjalankannya berisiko memasang malware.', '[{"id":"sender","label":"Alamat tidak dikenal","text":"Alamat pengirim memakai domain kirim-foto.click."},{"id":"body","label":"Instruksi menjalankan file","text":"Pesan meminta file dijalankan."},{"id":"attachment","label":"Ekstensi berbahaya","text":"Lampiran bernama AlbumFoto.exe."}]'::jsonb),
  (10, 'group-document-safe', 1, 'Revisi dokumen tugas kelompok', 'Calvin memperbarui bagian kesimpulan.', 'Halo,', 'Bagian kesimpulan sudah aku revisi. Silakan beri komentar langsung di dokumen sekolah.', 'Buka: https://dokumen.sekolah.id/tugas-kelompok', 'catatan-revisi.txt', '/assets/Shared/Game/FileText.png', false, 'Pengirim dikenal, konteks masuk akal, dan tautan berada di layanan resmi sekolah.', '[]'::jsonb),
  (11, 'fake-scholarship', 9, 'Selamat, kamu mendapat beasiswa penuh', 'Lengkapi data rekening hari ini.', 'Siswa terpilih,', 'Kamu dipilih tanpa proses seleksi. Kirim foto kartu pelajar, nomor rekening, dan PIN untuk pencairan.', 'Daftar: https://beasiswa-cepat.xyz', NULL, NULL, true, 'Beasiswa tanpa seleksi yang meminta PIN dan dokumen identitas melalui domain asing adalah penipuan.', '[{"id":"sender","label":"Pengirim tidak resmi","text":"Alamat tidak menggunakan domain sekolah."},{"id":"body","label":"Meminta data sensitif","text":"Pesan meminta foto identitas, rekening, dan PIN."},{"id":"action","label":"Domain asing","text":"Tautan memakai beasiswa-cepat.xyz."}]'::jsonb),
  (12, 'forum-invite-safe', 7, 'Undangan diskusi ilustrasi digital', 'Topik baru komunitas dibuka malam ini.', 'Halo Nico,', 'Diskusi ilustrasi digital dimulai pukul 19.00. Gunakan akun komunitas seperti biasa dan jangan bagikan kata sandi kepada siapa pun.', 'Buka: https://komunitasseni.id/forum/ilustrasi', NULL, NULL, false, 'Pesan memakai tautan komunitas resmi dan justru mengingatkan agar kata sandi tidak dibagikan.', '[]'::jsonb),
  (13, 'cloud-storage-full', 4, 'Penyimpanan sekolah 99% penuh', 'Masuk sekarang atau semua dokumen akan dihapus.', 'Pengguna,', 'Kotak penyimpananmu hampir penuh. Verifikasi akun dengan memasukkan kata sandi sebelum tengah malam.', 'Verifikasi: http://storage-sekolah.cloud/verify', NULL, NULL, true, 'Ancaman penghapusan, permintaan kata sandi, dan domain menyerupai sekolah adalah tanda phishing.', '[{"id":"sender","label":"Domain menyerupai sekolah","text":"Alamat memakai sekolah-storage.cloud."},{"id":"body","label":"Ancaman dan kata sandi","text":"Pesan mengancam penghapusan dan meminta kata sandi."},{"id":"action","label":"Tautan tidak resmi","text":"Tautan bukan portal.sekolah.id."}]'::jsonb),
  (14, 'admin-contact-safe', 9, 'Pembaruan kontak darurat siswa', 'Formulir resmi tersedia sampai Jumat.', 'Yth. orang tua dan siswa,', 'Silakan periksa kontak darurat melalui portal. Perubahan hanya dapat dilakukan setelah login langsung di portal sekolah.', 'Portal: https://portal.sekolah.id/profil/kontak', NULL, NULL, false, 'Proses diarahkan ke portal resmi dan tidak meminta data dikirim lewat balasan email.', '[]'::jsonb),
  (15, 'parcel-delivery-scam', 10, 'Paket hadiah turnamen tertahan', 'Bayar biaya kecil untuk menerima hadiah.', 'Pemenang turnamen,', 'Paketmu tertahan. Masukkan alamat rumah dan data kartu untuk membayar biaya pengiriman Rp2.000.', 'Bayar: https://paket-turnamen.site', NULL, NULL, true, 'Permintaan alamat dan data kartu untuk hadiah tak terduga melalui situs asing adalah penipuan.', '[{"id":"sender","label":"Pengirim asing","text":"Alamat pengirim bukan dari platform game resmi."},{"id":"body","label":"Meminta data pribadi dan kartu","text":"Pesan meminta alamat serta data kartu."},{"id":"action","label":"Tautan palsu","text":"Tautan memakai paket-turnamen.site."}]'::jsonb),
  (16, 'library-ticket-safe', 14, 'Konfirmasi tiket peminjaman buku', 'Permintaan peminjamanmu sudah tercatat.', 'Halo,', 'Tiket peminjaman BK-2048 sudah tercatat. Tunjukkan kartu pelajar langsung di meja perpustakaan saat mengambil buku.', 'Status: https://perpus.sekolah.id/tiket/BK-2048', NULL, NULL, false, 'Nomor tiket dan kanal sesuai konteks perpustakaan, tanpa permintaan rahasia melalui email.', '[]'::jsonb),
  (17, 'fake-video-call', 2, 'Undangan rapat wali kelas mendadak', 'Pasang aplikasi rapat khusus sebelum 10 menit.', 'Halo siswa,', 'Rapat dimulai segera. Unduh aplikasi khusus dari lampiran lalu abaikan peringatan keamanan Windows.', 'Jalankan lampiran untuk bergabung.', 'MeetingUpdate.scr', '/assets/Shared/Game/FileZip.png', true, 'Lampiran .scr dan instruksi mengabaikan peringatan keamanan merupakan tanda serangan malware.', '[{"id":"sender","label":"Alamat tiruan","text":"Pengirim memakai domain rapat-kelas.live."},{"id":"body","label":"Mengabaikan peringatan","text":"Pesan meminta penerima mengabaikan peringatan keamanan."},{"id":"attachment","label":"Lampiran berbahaya","text":"Lampiran berekstensi .scr."}]'::jsonb),
  (18, 'teacher-announcement-safe', 4, 'Pengumuman kegiatan kelas', 'Rencana kerja bakti hari Senin.', 'Anak-anak,', 'Hari Senin kita kerja bakti setelah pelajaran kedua. Bawa sarung tangan jika tersedia, tanpa perlu mengirim data apa pun.', 'Detail: https://portal.sekolah.id/pengumuman/kerja-bakti', NULL, NULL, false, 'Pesan berasal dari guru melalui domain resmi dan hanya berisi pengumuman kegiatan.', '[]'::jsonb),
  (19, 'social-account-takeover', 11, 'Akun senimu dilaporkan', 'Ajukan banding sebelum akun dihapus.', 'Kreator,', 'Akunmu menerima banyak laporan. Kirim kata sandi dan kode pemulihan untuk mengajukan banding.', 'Banding: https://pusat-bantuan-art.help', NULL, NULL, true, 'Layanan resmi tidak meminta kata sandi atau kode pemulihan melalui email.', '[{"id":"sender","label":"Domain bantuan palsu","text":"Alamat memakai pusat-bantuan-art.help."},{"id":"body","label":"Meminta rahasia akun","text":"Pesan meminta kata sandi dan kode pemulihan."},{"id":"action","label":"Tautan tidak resmi","text":"Halaman banding bukan domain komunitas resmi."}]'::jsonb),
  (20, 'game-friend-safe', 10, 'Jadwal turnamen komunitas', 'Pertandingan dimulai Sabtu pukul 15.00.', 'Halo tim,', 'Bracket turnamen sudah tersedia. Login hanya melalui aplikasi GameHub dan jangan percaya tautan hadiah dari pesan pribadi.', 'Jadwal: https://gamehub.id/turnamen', NULL, NULL, false, 'Tautan resmi dan pesan tidak meminta data sensitif.', '[]'::jsonb),
  (21, 'fake-tax-refund', 5, 'Pengembalian dana sekolah', 'Masukkan rekening dan PIN untuk menerima dana.', 'Yth. siswa,', 'Sekolah memiliki kelebihan pembayaran. Isi nomor rekening, PIN ATM, dan foto kartu identitas untuk proses hari ini.', 'Formulir: http://refund-sekolah.online', NULL, NULL, true, 'PIN ATM tidak pernah diperlukan untuk menerima transfer dan domain formulir bukan domain sekolah.', '[{"id":"sender","label":"Alamat palsu","text":"Pengirim memakai domain dana-sekolah.online."},{"id":"body","label":"Meminta PIN ATM","text":"Pesan meminta PIN dan foto identitas."},{"id":"action","label":"Formulir tidak resmi","text":"Tautan memakai refund-sekolah.online."}]'::jsonb),
  (22, 'photo-contest-safe', 3, 'Hasil lomba foto sekolah', 'Daftar pemenang diumumkan di portal.', 'Halo peserta,', 'Hasil lomba foto sudah diumumkan. Panitia tidak meminta biaya atau data bank dari pemenang.', 'Lihat: https://portal.sekolah.id/lomba-foto', 'pemenang.png', '/assets/Shared/Game/FilePhoto.png', false, 'Informasi tersedia pada portal resmi dan tidak meminta pembayaran maupun data bank.', '[]'::jsonb),
  (23, 'invoice-attachment', 6, 'Tagihan layanan internet belum dibayar', 'Buka faktur terlampir untuk menghindari denda.', 'Pelanggan,', 'Pembayaran gagal. Aktifkan makro pada dokumen terlampir agar detail tagihan dapat ditampilkan.', 'Buka lampiran dan pilih Enable Content.', 'Tagihan_Internet.zip', '/assets/Shared/Game/FileZip.png', true, 'Lampiran ZIP tak terduga dan instruksi mengaktifkan konten dapat menjalankan malware.', '[{"id":"sender","label":"Pengirim tidak dikenal","text":"Alamat memakai domain invoice-center.click."},{"id":"body","label":"Instruksi berbahaya","text":"Pesan meminta mengaktifkan konten atau makro."},{"id":"attachment","label":"Arsip tak terduga","text":"Tagihan dikirim sebagai berkas ZIP."}]'::jsonb),
  (24, 'school-survey-safe', 9, 'Survei fasilitas sekolah', 'Survei anonim ditutup hari Jumat.', 'Halo siswa,', 'Bagikan pendapat tentang perpustakaan dan kantin. Survei tidak meminta nama, email, atau kata sandi.', 'Isi: https://survey.sekolah.id/fasilitas', NULL, NULL, false, 'Survei memakai subdomain resmi dan menyatakan tidak mengumpulkan data pribadi.', '[]'::jsonb),
  (25, 'camera-access-scam', 12, 'Verifikasi wajah untuk membuka akun', 'Izinkan kamera dan unggah kartu pelajar.', 'Pengguna,', 'Kami harus memverifikasi wajahmu. Buka tautan, izinkan kamera, lalu unggah kartu pelajar dalam 20 menit.', 'Mulai: https://secure-face-check.live', NULL, NULL, true, 'Permintaan biometrik dan identitas melalui situs asing dengan tekanan waktu sangat berisiko.', '[{"id":"sender","label":"Identitas support palsu","text":"Alamat pengirim memakai layanan-akun.help."},{"id":"body","label":"Meminta biometrik dan identitas","text":"Pesan meminta wajah dan kartu pelajar."},{"id":"action","label":"Situs verifikasi asing","text":"Tautan memakai secure-face-check.live."}]'::jsonb),
  (26, 'support-ticket-safe', 12, 'Tiket bantuan #4821 diterima', 'Tim dukungan sedang memeriksa laporanmu.', 'Halo,', 'Laporan gangguan sudah diterima. Kami tidak akan meminta kata sandi atau OTP. Pantau status melalui pusat bantuan resmi.', 'Status: https://layanan.id/tiket/4821', NULL, NULL, false, 'Pesan hanya mengonfirmasi tiket melalui domain resmi dan tidak meminta rahasia akun.', '[]'::jsonb),
  (27, 'exam-result-scam', 8, 'Nilai ujian bocor lebih awal', 'Bayar untuk melihat hasil sebelum diumumkan.', 'Siswa,', 'Kami memiliki akses nilai ujian. Masukkan akun sekolah dan data pembayaran untuk membuka hasil sekarang.', 'Lihat: http://nilai-rahasia.store', NULL, NULL, true, 'Tawaran ilegal, permintaan login, dan pembayaran melalui domain asing adalah tanda penipuan.', '[{"id":"sender","label":"Alamat bukan milik guru","text":"Pengirim memakai nilai-cepat.store."},{"id":"subject","label":"Tawaran tidak wajar","text":"Subjek mengklaim nilai ujian bocor."},{"id":"action","label":"Tautan asing","text":"Tautan memakai nilai-rahasia.store."}]'::jsonb),
  (28, 'club-registration-safe', 13, 'Pendaftaran kegiatan tanam pohon', 'Pilih ukuran sarung tangan melalui formulir resmi.', 'Halo relawan,', 'Pendaftaran dibuka sampai Rabu. Formulir hanya meminta nama panggilan dan ukuran sarung tangan.', 'Daftar: https://komunitashijau.id/tanam-pohon', NULL, NULL, false, 'Permintaan data terbatas sesuai kegiatan dan memakai domain komunitas resmi.', '[]'::jsonb),
  (29, 'qr-login-phishing', 7, 'Pindai QR untuk mempertahankan akun', 'Sesi akan berakhir jika QR tidak dipindai.', 'Halo,', 'Pindai kode pada lampiran dan login kembali untuk mencegah semua pesan dihapus.', 'Pindai lampiran sebelum 5 menit.', 'QR-login.png', '/assets/Shared/Game/FilePhoto.png', true, 'QR tak terduga dapat menyembunyikan tautan phishing, terutama saat disertai ancaman dan batas waktu.', '[{"id":"sender","label":"Domain pengirim asing","text":"Alamat memakai forum-security.click."},{"id":"body","label":"Ancaman mendesak","text":"Pesan mengancam menghapus semua pesan."},{"id":"attachment","label":"QR login tak terduga","text":"Lampiran meminta pemindaian untuk login."}]'::jsonb),
  (30, 'shared-notes-safe', 2, 'Catatan belajar untuk ujian', 'Maya membagikan ringkasan materi.', 'Hai,', 'Ini catatan belajar yang kita susun tadi. Berkas hanya berisi ringkasan pelajaran tanpa data pribadi.', 'Tidak ada tindakan lain yang diperlukan.', 'ringkasan-ujian.txt', '/assets/Shared/Game/FileText.png', false, 'Pengirim dikenal, konteks sesuai, dan lampiran teks tidak meminta tindakan berisiko.', '[]'::jsonb),
  (31, 'account-appeal-scam', 1, 'Aktivitas mencurigakan ditemukan', 'Konfirmasi identitas sebelum pukul 18.00.', 'Pengguna,', 'Kami mendeteksi login dari luar negeri. Ketik email, kata sandi, dan OTP pada halaman pemeriksaan.', 'Periksa: https://akun-sekolah-security.com', NULL, NULL, true, 'Halaman verifikasi palsu meminta seluruh faktor autentikasi sekaligus.', '[{"id":"sender","label":"Domain look-alike","text":"Alamat menyerupai domain sekolah tetapi bukan sekolah.id."},{"id":"body","label":"Meminta seluruh kredensial","text":"Pesan meminta email, kata sandi, dan OTP."},{"id":"action","label":"Tautan look-alike","text":"Domain akun-sekolah-security.com bukan portal resmi."}]'::jsonb),
  (32, 'parent-meeting-safe', 4, 'Undangan pertemuan orang tua', 'Agenda dan jadwal tersedia di portal.', 'Yth. siswa,', 'Pertemuan orang tua berlangsung Jumat. Silakan sampaikan undangan ini dan cek jadwal kelas melalui portal resmi.', 'Jadwal: https://portal.sekolah.id/pertemuan-orang-tua', 'undangan.pdf', '/assets/Shared/Game/FileText.png', false, 'Isi sesuai tugas wali kelas, tautan resmi, dan tidak meminta data sensitif.', '[]'::jsonb),
  (33, 'charity-payment-scam', 13, 'Donasi darurat atas nama sekolah', 'Transfer sekarang untuk membantu korban.', 'Teman-teman,', 'Sekolah mewajibkan donasi hari ini. Masukkan data kartu atau transfer ke rekening pribadi panitia.', 'Donasi: https://donasi-sekolah.help', NULL, NULL, true, 'Kewajiban mendadak, rekening pribadi, dan situs asing menunjukkan penipuan.', '[{"id":"sender","label":"Pengirim meniru komunitas","text":"Alamat bukan domain komunitas atau sekolah."},{"id":"body","label":"Pembayaran ke rekening pribadi","text":"Pesan meminta transfer ke rekening pribadi."},{"id":"action","label":"Situs donasi palsu","text":"Tautan memakai donasi-sekolah.help."}]'::jsonb),
  (34, 'book-return-safe', 14, 'Pengingat pengembalian buku', 'Buku sains jatuh tempo tiga hari lagi.', 'Halo,', 'Buku sains perlu dikembalikan hari Senin. Perpanjangan dapat dilakukan sendiri melalui akun perpustakaan.', 'Perpanjang: https://perpus.sekolah.id/pinjaman', NULL, NULL, false, 'Pengingat wajar dan semua tindakan dilakukan di situs resmi perpustakaan.', '[]'::jsonb),
  (35, 'browser-update-malware', 5, 'Pembaruan browser wajib', 'Pasang pembaruan agar portal sekolah dapat dibuka.', 'Siswa,', 'Versi browsermu tidak didukung. Unduh patch terlampir, matikan antivirus, lalu jalankan sebagai administrator.', 'Jalankan berkas sekarang.', 'BrowserPatch.bat', '/assets/Shared/Game/FileZip.png', true, 'Instruksi mematikan antivirus dan menjalankan berkas .bat sebagai administrator sangat berbahaya.', '[{"id":"sender","label":"Domain teknis palsu","text":"Alamat memakai update-sekolah.tech."},{"id":"body","label":"Mematikan perlindungan","text":"Pesan meminta antivirus dimatikan."},{"id":"attachment","label":"Skrip berbahaya","text":"Lampiran berekstensi .bat."}]'::jsonb),
  (36, 'community-gallery-safe', 11, 'Galeri karya bulan ini', 'Karya anggota sudah dipublikasikan.', 'Halo seniman,', 'Galeri bulan ini sudah tayang. Jika ingin mengubah judul karya, lakukan melalui profil komunitas.', 'Galeri: https://komunitasseni.id/galeri', NULL, NULL, false, 'Domain resmi dan tindakan melalui profil komunitas menunjukkan pesan yang wajar.', '[]'::jsonb),
  (37, 'wifi-password-phish', 6, 'Akses Wi-Fi sekolah diperbarui', 'Kirim akun untuk menerima kata sandi baru.', 'Halo,', 'Jaringan sekolah berubah. Balas dengan username dan kata sandi akun sekolah agar aksesmu diaktifkan.', 'Balas sebelum kelas dimulai.', NULL, NULL, true, 'Administrator jaringan tidak perlu mengetahui kata sandi pengguna untuk memberi akses Wi-Fi.', '[{"id":"sender","label":"Domain jaringan palsu","text":"Alamat memakai wifi-sekolah.network."},{"id":"body","label":"Meminta kata sandi","text":"Pesan meminta username dan kata sandi."},{"id":"action","label":"Tekanan waktu","text":"Penerima ditekan untuk membalas sebelum kelas."}]'::jsonb),
  (38, 'competition-certificate-safe', 3, 'Sertifikat lomba foto tersedia', 'Unduh sertifikat dari portal sekolah.', 'Halo peserta,', 'Sertifikat digital sudah tersedia di akun masing-masing. Pastikan alamat tetap portal.sekolah.id sebelum login.', 'Unduh: https://portal.sekolah.id/sertifikat', NULL, NULL, false, 'Pesan mengarahkan ke portal resmi dan mengingatkan penerima memeriksa domain.', '[]'::jsonb),
  (39, 'fake-copyright-claim', 11, 'Pelanggaran hak cipta pada karyamu', 'Buka bukti pelanggaran dalam lampiran.', 'Pemilik akun,', 'Karyamu dilaporkan. Ekstrak bukti terlampir dan jalankan aplikasi pemeriksa untuk menghindari penutupan akun.', 'Buka lampiran hari ini.', 'CopyrightEvidence.zip', '/assets/Shared/Game/FileZip.png', true, 'Arsip tak terduga dan instruksi menjalankan aplikasi adalah teknik penyebaran malware.', '[{"id":"sender","label":"Alamat hukum palsu","text":"Pengirim memakai copyright-alert.legal."},{"id":"body","label":"Ancaman penutupan akun","text":"Pesan menekan penerima agar menjalankan aplikasi."},{"id":"attachment","label":"Arsip mencurigakan","text":"Bukti dikirim sebagai berkas ZIP."}]'::jsonb),
  (40, 'study-group-safe', 1, 'Lokasi belajar kelompok berubah', 'Pertemuan dipindah ke perpustakaan sekolah.', 'Hai semua,', 'Belajar kelompok dipindah ke perpustakaan pukul 14.00. Jangan bagikan jadwal ini di akun publik.', 'Tidak ada tautan atau lampiran.', NULL, NULL, false, 'Pesan dari teman dikenal, tanpa tautan, lampiran, atau permintaan data rahasia.', '[]'::jsonb),
  (41, 'crypto-investment-scam', 10, 'Gandakan uang sakumu dalam sehari', 'Program investasi khusus pelajar.', 'Pemain hebat,', 'Kirim data rekening dan transfer modal awal. Keuntungan 500% dijamin kembali malam ini.', 'Investasi: https://pelajar-cuan.pro', NULL, NULL, true, 'Janji keuntungan tidak masuk akal dan permintaan transfer merupakan ciri penipuan investasi.', '[{"id":"sender","label":"Pengirim bukan platform resmi","text":"Alamat memakai game-invest.pro."},{"id":"subject","label":"Janji keuntungan instan","text":"Subjek menjanjikan uang berlipat dalam sehari."},{"id":"action","label":"Situs investasi asing","text":"Tautan memakai pelajar-cuan.pro."}]'::jsonb),
  (42, 'grade-consultation-safe', 8, 'Jadwal konsultasi nilai', 'Pilih waktu konsultasi di portal.', 'Halo siswa,', 'Jika ada pertanyaan tentang nilai, pilih jadwal konsultasi. Nilai lengkap tidak akan dikirim melalui email.', 'Pilih jadwal: https://portal.sekolah.id/konsultasi', NULL, NULL, false, 'Proses melalui portal resmi dan guru tidak mengirim data akademik sensitif lewat email.', '[]'::jsonb),
  (43, 'fake-vaccine-form', 9, 'Data kesehatan wajib dikirim hari ini', 'Unggah rekam medis dan nomor identitas.', 'Yth. siswa,', 'Untuk mengikuti kelas besok, unggah seluruh rekam medis, foto identitas, dan alamat rumah pada formulir berikut.', 'Unggah: http://data-siswa-health.site', NULL, NULL, true, 'Permintaan data kesehatan dan identitas yang berlebihan melalui domain asing melanggar prinsip minimisasi data.', '[{"id":"sender","label":"Alamat administrasi palsu","text":"Pengirim bukan dari sekolah.id."},{"id":"body","label":"Meminta data berlebihan","text":"Pesan meminta rekam medis, identitas, dan alamat rumah."},{"id":"action","label":"Formulir tidak resmi","text":"Tautan memakai data-siswa-health.site."}]'::jsonb),
  (44, 'eco-newsletter-safe', 13, 'Buletin kegiatan hijau Agustus', 'Ringkasan kegiatan dan agenda berikutnya.', 'Halo anggota,', 'Terima kasih sudah ikut bersih taman. Buletin ini memuat dokumentasi kegiatan dan jadwal publik berikutnya.', 'Baca: https://komunitashijau.id/buletin/agustus', 'kegiatan-agustus.png', '/assets/Shared/Game/FilePhoto.png', false, 'Konten informatif, domain resmi, dan tidak ada permintaan data sensitif.', '[]'::jsonb),
  (45, 'fake-prize-survey', 2, 'Isi survei dan dapatkan ponsel baru', 'Hanya lima menit untuk mengklaim hadiah.', 'Pengunjung beruntung,', 'Isi nomor telepon, alamat rumah, data kartu, dan OTP untuk biaya pengiriman hadiah.', 'Klaim: https://survei-hadiah.click', NULL, NULL, true, 'Hadiah mendadak yang meminta data kartu dan OTP adalah penipuan.', '[{"id":"sender","label":"Domain hadiah palsu","text":"Alamat memakai hadiah-pelajar.click."},{"id":"body","label":"Meminta data sensitif","text":"Pesan meminta data kartu dan OTP."},{"id":"action","label":"Tautan hadiah asing","text":"Tautan memakai survei-hadiah.click."}]'::jsonb),
  (46, 'account-recovery-safe', 12, 'Permintaan pemulihan akun dibatalkan', 'Tidak ada perubahan pada akunmu.', 'Halo,', 'Permintaan pemulihan dibatalkan karena tidak dikonfirmasi. Jika ini bukan tindakanmu, buka aplikasi resmi dan hubungi pusat bantuan. Kami tidak akan meminta OTP.', 'Bantuan: https://layanan.id/keamanan', NULL, NULL, false, 'Pesan memakai domain resmi dan tidak meminta penerima memberikan rahasia autentikasi.', '[]'::jsonb),
  (47, 'fake-calendar-share', 4, 'Kalender ujian dibagikan kepadamu', 'Login untuk melihat jadwal rahasia.', 'Siswa,', 'Kalender ujian baru dibagikan. Masukkan akun sekolah pada halaman eksternal agar undangan diterima.', 'Terima: https://calendar-sekolah-share.com', NULL, NULL, true, 'Halaman eksternal yang meminta login sekolah dapat mencuri kredensial.', '[{"id":"sender","label":"Alamat undangan palsu","text":"Pengirim memakai calendar-share.email."},{"id":"body","label":"Meminta login eksternal","text":"Pesan meminta akun sekolah dimasukkan di halaman luar."},{"id":"action","label":"Domain look-alike","text":"calendar-sekolah-share.com bukan domain sekolah."}]'::jsonb),
  (48, 'file-request-safe', 3, 'Mohon kirim versi final poster kelas', 'Raka meminta berkas tanpa data pribadi.', 'Hai,', 'Boleh kirim poster versi final? Pastikan nama lengkap dan nomor telepon tidak tercantum sebelum dikirim.', 'Balas dengan berkas poster final.', NULL, NULL, false, 'Permintaan berasal dari teman dikenal dan secara jelas menghindari data pribadi.', '[]'::jsonb),
  (49, 'fake-security-audit', 5, 'Audit keamanan akun siswa', 'Instal alat pemeriksa resmi dari lampiran.', 'Pengguna,', 'Akunmu harus diaudit. Nonaktifkan antivirus lalu instal alat terlampir menggunakan hak administrator.', 'Instal sebelum pukul 17.00.', 'SecurityAudit.exe', '/assets/Shared/Game/FileZip.png', true, 'Tidak ada audit resmi yang meminta antivirus dimatikan dan program .exe asing dijalankan sebagai administrator.', '[{"id":"sender","label":"Alamat staf palsu","text":"Pengirim memakai audit-sekolah.systems."},{"id":"body","label":"Instruksi berbahaya","text":"Pesan meminta antivirus dinonaktifkan."},{"id":"attachment","label":"Program tak dikenal","text":"Lampiran berupa SecurityAudit.exe."}]'::jsonb),
  (50, 'closing-library-safe', 14, 'Perpustakaan tutup lebih awal', 'Jam layanan hari Jumat berubah.', 'Halo siswa,', 'Perpustakaan tutup pukul 14.00 pada hari Jumat karena pemeliharaan. Pengembalian dapat dilakukan melalui kotak buku.', 'Info: https://perpus.sekolah.id/pengumuman', NULL, NULL, false, 'Pengumuman operasional berasal dari domain resmi dan tidak meminta tindakan sensitif.', '[]'::jsonb)
),
senders AS (
  SELECT
    ARRAY['Calvin Wu','Maya Putri','Raka Pradana','Pak Dimas','Arman Setiawan','Reno Aditya','Nico Grey','Pak Budi Santoso','Bu Aisyah','PixelRex','Naya Bloom','Alex Support','Sari Mahendra','Bu Ratna']::text[] AS names,
    ARRAY['calvin.wu@sekolah.id','maya.putri@sekolah.id','raka.pradana@sekolah.id','dimas@sekolah.id','arman.setiawan@sekolah.id','reno.aditya@sekolah.id','nico.grey@komunitas.id','budi.santoso@sekolah.id','aisyah@sekolah.id','pixelrex@gamehub.id','naya.bloom@komunitasseni.id','support@layanan.id','sari.mahendra@komunitashijau.id','ratna@sekolah.id']::text[] AS safe_emails,
    ARRAY['calvin.wu@sekolah-share.click','maya.putri@hadiah-pelajar.click','raka.pradana@foto-kelas.click','dimas@calendar-share.email','arman.setiawan@staf-sekolah.help','reno.aditya@kirim-foto.click','nico.grey@forum-security.click','budi.santoso@nilai-cepat.store','aisyah@admin-sekolah.support','pixelrex@game-invest.pro','naya.bloom@copyright-alert.legal','alex.support@layanan-akun.help','sari.mahendra@donasi-sekolah.help','ratna@perpus-bayar.top']::text[] AS phishing_emails
)
INSERT INTO "MsPhishingQuestion" (
  "id", "sequence", "senderName", "senderEmail", "senderAsset", "subject", "preview", "greeting", "body", "action", "attachmentName", "attachmentAsset", "suspicious", "explanation", "clues", "updatedAt"
)
SELECT
  q."id",
  q."sequence",
  s.names[q."senderSlot"],
  CASE WHEN q."suspicious" THEN s.phishing_emails[q."senderSlot"] ELSE s.safe_emails[q."senderSlot"] END,
  '/assets/Game1/characters/chara' || q."senderSlot" || '.png',
  q."subject",
  q."preview",
  q."greeting",
  q."body",
  q."action",
  q."attachmentName",
  q."attachmentAsset",
  q."suspicious",
  q."explanation",
  q."clues",
  CURRENT_TIMESTAMP
FROM questions q
CROSS JOIN senders s;
