INSERT INTO "MsPrivacyQuestion" (
    "id", "sequence", "characterName", "characterAsset", "accountAge", "relationship",
    "prompt", "explanation", "correctFeedback", "correctChoice", "isActive", "createdAt", "updatedAt"
) VALUES
('privacy-51', 51, 'Aruna', '/assets/Game1/characters/chara1.png', '11 bulan', 'Akun filter foto tidak resmi', 'Aruna meminta sidik jarimu untuk membuka efek eksklusif di aplikasi filter. Bagikan?', 'Sidik jari adalah data biometrik permanen yang tidak diperlukan oleh aplikasi filter dan berisiko disalahgunakan.', 'Pilihan tepat: jangan menyerahkan data biometrik kepada aplikasi yang tidak resmi.', 'REJECT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-52', 52, 'Bagas', '/assets/Game1/characters/chara2.png', '18 bulan', 'Guru bahasa melalui portal sekolah', 'Bagas meminta rekaman suaramu saat membaca teks untuk penilaian pelafalan. Bagikan?', 'Rekaman suara relevan untuk tugas pelafalan dan dikirim terbatas melalui portal sekolah kepada guru.', 'Pilihan tepat: rekaman tugas dapat dibagikan melalui kanal resmi kepada guru yang berwenang.', 'SHARE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-53', 53, 'Cantika', '/assets/Game1/characters/chara3.png', '2 tahun 3 bulan', 'Calon pembeli tiket di media sosial', 'Cantika meminta foto tiket konser yang memperlihatkan kode QR sebelum membayar. Bagikan?', 'Kode QR tiket dapat dipindai atau disalin sehingga tiketmu bisa digunakan orang lain.', 'Pilihan tepat: sembunyikan kode QR dan gunakan mekanisme transfer tiket yang resmi.', 'REJECT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-54', 54, 'Danang', '/assets/Game1/characters/chara4.png', '9 hari', 'Panitia resmi kemah sekolah', 'Danang meminta informasi alergi makanan melalui formulir resmi untuk menyiapkan konsumsi. Bagikan?', 'Informasi alergi diperlukan untuk keselamatan peserta dan diberikan kepada panitia resmi dengan tujuan yang jelas.', 'Pilihan tepat: data alergi dapat dibagikan secara terbatas untuk kebutuhan keselamatan acara.', 'SHARE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-55', 55, 'Elara', '/assets/Game1/characters/chara5.png', '7 bulan', 'Moderator komunitas kerajinan', 'Elara meminta jenis kerajinan yang kamu sukai untuk ditampilkan di profil publik komunitas. Bagikan?', 'Hobi kerajinan adalah minat umum yang boleh ditampilkan jika kamu nyaman dan tidak disertai data pribadi lain.', 'Pilihan tepat: hobi umum dapat dibagikan secara publik sesuai kenyamananmu.', 'SHARE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-56', 56, 'Fikri', '/assets/Game1/characters/chara6.png', '3 tahun 2 bulan', 'Rekan satu tim proyek', 'Fikri meminta akses ke dokumen bersama yang hanya berisi agenda dan pembagian tugas kelompok. Bagikan?', 'Dokumen tersebut berisi informasi proyek yang memang diperlukan oleh anggota tim dan tidak memuat data sensitif.', 'Pilihan tepat: berikan akses dokumen sesuai kebutuhan kepada anggota tim terkait.', 'SHARE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-57', 57, 'Gendis', '/assets/Game1/characters/chara7.png', '26 hari', 'Dukungan resmi produsen perangkat', 'Gendis meminta nomor seri perangkat melalui portal dukungan resmi untuk memeriksa garansi. Bagikan?', 'Nomor seri relevan untuk pemeriksaan garansi jika diberikan melalui portal resmi dan bukan dipublikasikan.', 'Pilihan tepat: nomor seri dapat diberikan secara privat kepada dukungan resmi untuk layanan perangkat.', 'SHARE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-58', 58, 'Haikal', '/assets/Game1/characters/chara8.png', '14 bulan', 'Kenalan baru dari forum', 'Haikal meminta jadwal kegiatanmu selama seminggu agar tahu kapan kamu berada di luar rumah. Bagikan?', 'Jadwal pribadi yang rinci dapat mengungkap pola keberadaan dan meningkatkan risiko keamanan.', 'Pilihan tepat: jangan bagikan jadwal pribadi terperinci kepada kenalan baru.', 'REJECT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-59', 59, 'Isyana', '/assets/Game1/characters/chara9.png', '5 bulan', 'Situs undian tidak dikenal', 'Isyana meminta pemindaian wajah dari beberapa sudut untuk mengklaim kupon belanja. Bagikan?', 'Pindaian wajah adalah data biometrik yang dapat disalahgunakan dan tidak sebanding dengan tujuan undian.', 'Pilihan tepat: tolak pengumpulan data wajah oleh situs undian yang tidak tepercaya.', 'REJECT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-60', 60, 'Jovian', '/assets/Game1/characters/chara10.png', '4 tahun 6 bulan', 'Petugas administrasi sekolah', 'Jovian meminta nama dan nomor kontak darurat orang tua melalui formulir pendaftaran resmi sekolah. Bagikan?', 'Kontak darurat diperlukan agar sekolah dapat menghubungi pihak yang tepat saat terjadi keadaan mendesak.', 'Pilihan tepat: kontak darurat dapat diberikan kepada sekolah melalui formulir resminya.', 'SHARE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-61', 61, 'Kania', '/assets/Game1/characters/chara11.png', '12 hari', 'Akun bantuan palsu', 'Kania meminta salah satu kode pemulihan sekali pakai untuk memperbaiki akunmu. Bagikan?', 'Kode pemulihan dapat melewati perlindungan login dan memberikan akses langsung ke akun.', 'Pilihan tepat: semua kode pemulihan harus disimpan rahasia dan tidak dikirim kepada siapa pun.', 'REJECT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-62', 62, 'Mahesa', '/assets/Game1/characters/chara12.png', '8 bulan', 'Kurir melalui nomor pribadi', 'Mahesa meminta kode akses pintu apartemen agar paket bisa ditaruh di depan unit saat kamu pergi. Bagikan?', 'Kode akses apartemen membuka area privat dan tidak boleh diberikan kepada kurir melalui percakapan pribadi.', 'Pilihan tepat: gunakan prosedur penerimaan resmi tanpa membagikan kode akses tempat tinggal.', 'REJECT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-63', 63, 'Nayla', '/assets/Game1/characters/chara13.png', '6 tahun 1 bulan', 'Dokter di layanan telemedisin resmi', 'Nayla meminta catatan tekanan darah terbaru dalam konsultasi privat untuk menilai pengobatan. Bagikan?', 'Catatan kesehatan relevan bagi dokter yang menangani dan dikirim melalui layanan telemedisin resmi yang privat.', 'Pilihan tepat: data kesehatan dapat dibagikan secara terbatas kepada tenaga medis yang menangani.', 'SHARE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-64', 64, 'Pradipta', '/assets/Game1/characters/chara14.png', '21 hari', 'Panitia beasiswa sekolah', 'Pradipta meminta nomor induk siswa pada portal resmi untuk mencocokkan berkas pendaftaran beasiswa. Bagikan?', 'Nomor induk diperlukan untuk verifikasi berkas jika dimasukkan langsung ke portal resmi sekolah.', 'Pilihan tepat: identitas akademik dapat diberikan secara terbatas melalui sistem resmi yang membutuhkannya.', 'SHARE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-65', 65, 'Rania', '/assets/Game1/characters/chara1.png', '32 hari', 'Situs kuis hiburan', 'Rania meminta seluruh riwayat pencarian browser untuk menebak kepribadianmu. Bagikan?', 'Riwayat pencarian dapat mengungkap minat, masalah pribadi, dan aktivitas sensitif yang tidak diperlukan oleh kuis hiburan.', 'Pilihan tepat: jangan serahkan riwayat penelusuran kepada situs kuis.', 'REJECT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-66', 66, 'Seno', '/assets/Game1/characters/chara2.png', '10 bulan', 'Koordinator aksesibilitas acara', 'Seno meminta kebutuhan tempat duduk aksesibel melalui formulir privat agar lokasi acara dapat disiapkan. Bagikan?', 'Kebutuhan aksesibilitas relevan untuk menyiapkan akomodasi dan disampaikan secara privat kepada koordinator resmi.', 'Pilihan tepat: bagikan kebutuhan aksesibilitas seperlunya kepada penyelenggara yang bertanggung jawab.', 'SHARE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-67', 67, 'Talita', '/assets/Game1/characters/chara3.png', '17 hari', 'Kenalan dari komunitas menulis', 'Talita meminta tautan cadangan jurnal pribadimu agar bisa memahami gaya tulisanmu. Bagikan?', 'Jurnal pribadi dapat memuat pikiran dan pengalaman sensitif yang tidak diperlukan untuk menilai gaya tulisan.', 'Pilihan tepat: kirim contoh tulisan yang dipilih, bukan akses ke jurnal pribadi.', 'REJECT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-68', 68, 'Umar', '/assets/Game1/characters/chara4.png', '2 tahun 8 bulan', 'Koordinator magang terverifikasi', 'Umar meminta tautan portofolio publik untuk menilai hasil karya sebelum wawancara. Bagikan?', 'Portofolio publik memang disiapkan untuk menunjukkan karya dan permintaannya relevan dengan proses magang.', 'Pilihan tepat: tautan karya publik aman dibagikan kepada koordinator yang terverifikasi.', 'SHARE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-69', 69, 'Velia', '/assets/Game1/characters/chara5.png', '45 hari', 'Teknisi yang belum dijadwalkan', 'Velia meminta akses langsung ke kamera rumah untuk mendiagnosis jaringan sebelum kunjungan disepakati. Bagikan?', 'Siaran kamera rumah memperlihatkan ruang privat dan tidak perlu diberikan kepada teknisi yang belum terverifikasi jadwalnya.', 'Pilihan tepat: jangan berikan akses kamera rumah; gunakan pemeriksaan resmi yang tidak membuka ruang privat.', 'REJECT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('privacy-70', 70, 'Yudha', '/assets/Game1/characters/chara6.png', '13 bulan', 'Pembeli anonim di lokapasar', 'Yudha meminta foto lengkap surat kendaraan sebelum bersedia melihat barang yang dijual. Bagikan?', 'Surat kendaraan memuat identitas dan rincian kepemilikan yang dapat disalahgunakan oleh pembeli anonim.', 'Pilihan tepat: lindungi dokumen kendaraan dan gunakan proses verifikasi resmi saat transaksi.', 'REJECT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
